### PR TITLE
chore: update README.md

### PR DESCRIPTION
**Pull request by ajays97**
Ticket: WIN-1511

### CODE REVIEW

**Review by sachushaji — APPROVED** [review]

**Review by Rachale43 — COMMENTED** [review]
Thank u

**Comment by surewire1920** [comment]
Hello handsome👍 would you mind we discusse some business here.

**Review by surewire1920 — APPROVED** [review]

**Comment by Waldo626em** [comment]
What do you mean?

**Review by Armss9936 — APPROVED** [review]

**Review by yumbo160480 — APPROVED** [review]

**Review by Waldo626em — COMMENTED** [review]
..

**Pull request merged**
